Adds user file
dpeshevski/semos-generation-13-git-github pull request #2
Opened 2021-03-24 21:06 UTC by dpeshevski

2021-03-24 21:09 UTC, meto2208 requested changes

2021-03-24 21:09 UTC, meto2208 commented on index.html
> +
odlicen proekt

2021-03-24 21:09 UTC, meto2208 commented on newuserfile.txt
> +User file
wrong test

2021-03-24 21:10 UTC, dpeshevski commented on index.html
> +
thanks

2021-03-24 21:10 UTC, dpeshevski commented on newuserfile.txt
> +User file
it's correct :)

2021-03-24 21:13 UTC, meto2208 approved these changes

2021-03-24 21:14 UTC, merged

2021-03-25 19:12 UTC, emillija reviewed
Dali uspeav da pullnam request?

2021-03-25 19:12 UTC, emillija commented on index.html
> +  <title>Document</title>
**25.03.2021**

2021-03-25 19:12 UTC, emillija commented on newuserfile.txt
> +User file
it's not

2021-03-25 19:15 UTC, emillija commented on index.html
> +  <title>Document</title>
blabla